### ISSUE TITLE
Flaky tests in CI run-tests-tsan step

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1907]
https://github.com/project-oak/oak/pull/1906/checks?check_run_id=2070457643#step:6:8196

```
tests ❯ cargo test (tsan) ║ thread 'test_leaks' panicked at 'Leak of Nodes or channels found', abitest/module_0/rust/tests/integration_test.rs:211:13
tests ❯ cargo test (tsan) ║ stack backtrace:
tests ❯ cargo test (tsan) ║    0: std::panicking::begin_panic
tests ❯ cargo test (tsan) ║              at /usr/local/cargo/toolchains/nightly-2020-10-19-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:505:12
tests ❯ cargo test (tsan) ║    1: integration_test::test_leaks::{{closure}}::{{closure}}
tests ❯ cargo test (tsan) ║              at ./tests/integration_test.rs:211:13
tests ❯ cargo test (tsan) ║    2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
tests ❯ cargo test (tsan) ║              at /usr/local/cargo/toolchains/nightly-2020-10-19-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
tests ❯ cargo test (tsan) ║    3: tokio::runtime::enter::Enter::block_on::{{closure}}
tests ❯ cargo test (tsan) ║              at /home/docker/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/enter.rs:160:58
tests ❯ cargo test (tsan) ║    4: tokio::coop::with_budget::{{closure}}
tests ❯ cargo test (tsan) ║              at /home/docker/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/coop.rs:127:9
tests ❯ cargo test (tsan) ║    5: std::thread::local::LocalKey<T>::try_with
tests ❯ cargo test (tsan) ║              at /usr/local/cargo/toolchains/nightly-2020-10-19-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
tests ❯ cargo test (tsan) ║    6: std::thread::local::LocalKey<T>::with
tests ❯ cargo test (tsan) ║              at /usr/local/cargo/toolchains/nightly-2020-10-19-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
tests ❯ cargo test (tsan) ║    7: tokio::coop::with_budget
tests ❯ cargo test (tsan) ║              at /home/docker/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/coop.rs:120:5
tests ❯ cargo test (tsan) ║    8: tokio::coop::budget
tests ❯ cargo test (tsan) ║              at /home/docker/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/coop.rs:96:5
tests ❯ cargo test (tsan) ║    9: tokio::runtime::enter::Enter::block_on
tests ❯ cargo test (tsan) ║              at /home/docker/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/enter.rs:160:35
tests ❯ cargo test (tsan) ║   10: tokio::runtime::thread_pool::ThreadPool::block_on
tests ❯ cargo test (tsan) ║              at /home/docker/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/thread_pool/mod.rs:82:9
tests ❯ cargo test (tsan) ║   11: tokio::runtime::Runtime::block_on::{{closure}}
tests ❯ cargo test (tsan) ║              at /home/docker/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/mod.rs:446:39
tests ❯ cargo test (tsan) ║   12: tokio::runtime::context::enter
tests ❯ cargo test (tsan) ║              at /home/docker/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/context.rs:72:5
tests ❯ cargo test (tsan) ║   13: tokio::runtime::handle::Handle::enter
tests ❯ cargo test (tsan) ║              at /home/docker/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/handle.rs:76:9
tests ❯ cargo test (tsan) ║   14: tokio::runtime::Runtime::block_on
tests ❯ cargo test (tsan) ║              at /home/docker/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/mod.rs:441:9
tests ❯ cargo test (tsan) ║   15: integration_test::test_leaks::{{closure}}
tests ❯ cargo test (tsan) ║              at ./tests/integration_test.rs:124:1
tests ❯ cargo test (tsan) ║   16: core::ops::function::FnOnce::call_once
tests ❯ cargo test (tsan) ║              at /usr/local/cargo/toolchains/nightly-2020-10-19-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
tests ❯ cargo test (tsan) ║   17: serial_test::serial_core
tests ❯ cargo test (tsan) ║              at /home/docker/.cargo/registry/src/github.com-1ecc6299db9ec823/serial_test-0.5.0/src/lib.rs:64:5
tests ❯ cargo test (tsan) ║   18: integration_test::test_leaks
tests ❯ cargo test (tsan) ║              at ./tests/integration_test.rs:125:1
tests ❯ cargo test (tsan) ║   19: integration_test::test_leaks::{{closure}}
tests ❯ cargo test (tsan) ║              at ./tests/integration_test.rs:124:1
tests ❯ cargo test (tsan) ║   20: core::ops::function::FnOnce::call_once
tests ❯ cargo test (tsan) ║              at /usr/local/cargo/toolchains/nightly-2020-10-19-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
tests ❯ cargo test (tsan) ║   21: core::ops::function::FnOnce::call_once
tests ❯ cargo test (tsan) ║              at /usr/local/cargo/toolchains/nightly-2020-10-19-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
tests ❯ cargo test (tsan) ║ note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
tests ❯ cargo test (tsan) ║ error: test failed, to rerun pass '--test integration_test'
```

**Comment by rbehjati** [comment]
Another example: https://github.com/project-oak/oak/runs/2079613863?check_suite_focus=true
```
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelCloseRaw (16=>16 nodes, 32=>32 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] NodeLabelRead (got 16=>16 nodes, 31=>32 channels, want 16=>16 nodes, 31=>31 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] GrpcServerFailNoHandle (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelHandleRecovered (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] ChannelReadOrphan (got 16=>16 nodes, 31=>32 channels, want 16=>16 nodes, 31=>31 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] BackendRoundtrip (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] GrpcServerFailReadHandle (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] CryptoAEAD (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] NodeCreateRaw (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelReadRaw (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelRead (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] HttpServerFailReadHandle (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] CryptoDAEAD (got 16=>16 nodes, 31=>32 channels, want 16=>16 nodes, 31=>31 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] RandomGet (got 16=>16 nodes, 31=>32 channels, want 16=>16 nodes, 31=>31 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] GrpcServerFailTwoHandles (got 16=>16 nodes, 31=>32 channels, want 16=>16 nodes, 31=>31 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] GrpcServerInvalidAddress (got 16=>16 nodes, 32=>31 channels, want 16=>16 nodes, 32=>32 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] HttpServerInvalidAddress (got 16=>16 nodes, 31=>32 channels, want 16=>16 nodes, 31=>31 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelWriteHandle (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelHandleReuse (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] Log (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] CryptoPRF (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] HttpServerPseudoNodePrivilege (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] CryptoFailSignature (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelChainRecovered (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] RandomGetRaw (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] HttpServerReservedPort (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] HttpServerFailTwoHandles (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] CryptoMac (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] CryptoFailBind (16=>16 nodes, 31=>31 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelChainLeaked (16=>16 nodes, 31=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelWriteOrphanFull (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] CryptoFailPRF (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] WaitOnChannelsRaw (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelWrite (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] NodeCreate (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] HttpServerFailNoHandle (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] CryptoBind (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelWriteOrphanEmpty (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelClose (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] WaitOnChannelsOrphan (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] CryptoFailDAEAD (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] CryptoFailMac (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelChainLost (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] CryptoSignature (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelCreate (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelWriteRaw (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] ChannelLabelReadRaw (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] DirectLog (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] GrpcServerPseudoNodePrivilege (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] LinearHandles (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelReadWithDowngrade (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] RandomRng (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] WaitOnChannelsWithDowngrade (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] LoggerPseudoNodePrivilege (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] CryptoFailAEAD (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] ChannelCreateRaw (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] WaitOnChannels (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] NodePrivilegeReadRaw (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] HttpClientPseudoNodePrivilege (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] HandleCloneRaw (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] ChannelLabelRead (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ OK ] NodePrivilegeRead (16=>16 nodes, 40=>40 channels, as expected)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] NodeLabelReadRaw (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)
tests ❯ cargo test (tsan) ║ [2021-03-10T20:05:49Z INFO  integration_test] [ LEAK ] NodePanic (got 16=>16 nodes, 40=>41 channels, want 16=>16 nodes, 40=>40 channels)

```
