### ISSUE TITLE
Cannot run `xtask run-launcher-test` from our Docker development container

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#3598]
Although we give Docker access [--device=/dev/kvm](https://github.com/project-oak/oak/blob/22586daab5a488d53a5e552ce3f2523ad3fbe09a/.devcontainer.json#L28) and add ourselves to the group in the Docker container I get

```
# ls -ld /dev/kvm
crw-rw---- 1 nobody nogroup 10, 232 Jan 10 22:43 /dev/kvm
```

which results in

```bash

$ xtask run-launcher-test
[...]
target/x86_64-unknown-linux-musl/debug/xtask run-launcher-test`
[16:52:11 ✓:0,✗:0,⠇:2] ┌[End-to-end tests for the launcher and enclave binary]
[16:52:11 ✓:0,✗:0,⠇:2] │┌[run Virtual variant]
[16:52:11 ✓:0,✗:0,⠇:2] ││┌[build stage0]
[16:52:11 ✓:0,✗:0,⠇:2] │││ cargo objcopy --release -- -O binary target/x86_64-unknown-none/release/oak_stage0.bin (in directory ./stage0)
[16:52:14 ✓:0,✗:0,⠇:2] ││└─▶OK 3s
[16:52:14 ✓:0,✗:0,⠇:2] ││┌[build Oak Functions loader]
[16:52:14 ✓:0,✗:0,⠇:2] │││ cargo build (in directory ./oak_functions_launcher)
[16:53:09 ✓:0,✗:0,⠇:2] ││└─▶OK 55s
[16:53:09 ✓:0,✗:0,⠇:2] ││┌[build Oak Functions enclave binary]
[16:53:09 ✓:0,✗:0,⠇:2] │││ cargo build (in directory ./oak_functions_enclave)
[16:53:14 ✓:0,✗:0,⠇:2] ││└─▶OK 5s
[16:53:14 ✓:0,✗:0,⠇:2] ││┌[background loader]
[16:53:14 ✓:0,✗:0,⠇:2] │││ ./target/debug/oak_functions_launcher --wasm=./oak_functions_launcher/key_value_lookup.wasm --lookup-data=./oak_functions_launcher/mock_lookup_data virtual --enclave-binary=./oak_functions_enclave/target/x86_64-unknown-none/debug/oak_functions_enclave --vmm-binary=/usr/bin/qemu-system-x86_64 --bios-binary=./stage0/target/x86_64-unknown-none/release/oak_stage0.bin
[16:53:21 ✓:0,✗:0,⠇:2] │││┌[build and run client]
[16:53:21 ✓:0,✗:0,⠇:2] ││││┌[build client binary]
[16:53:21 ✓:0,✗:0,⠇:2] │││││ cargo build (in directory ./oak_functions_client)
[16:54:00 ✓:0,✗:0,⠇:2] ││││└─▶OK 40s
[16:54:00 ✓:0,✗:0,⠇:2] ││││┌[run client]
[16:54:00 ✓:0,✗:0,⠇:2] │││││ ./target/debug/oak_functions_client --request=test_key --expected-response-pattern=^test_value$ --iterations=300
[16:54:01 ✓:0,✗:0,⠇:2] │││││ ╔════════════════════════
[16:54:01 ✓:0,✗:0,⠇:2] │││││ ║ ════╡ stderr ╞════
[16:54:01 ✓:0,✗:0,⠇:2] │││││ ║ Error: couldn't create Oak Functions client
[16:54:01 ✓:0,✗:0,⠇:2] │││││ ║ 
[16:54:01 ✓:0,✗:0,⠇:2] │││││ ║ Caused by:
[16:54:01 ✓:0,✗:0,⠇:2] │││││ ║     0: couldn't create Oak Functions client
[16:54:01 ✓:0,✗:0,⠇:2] │││││ ║     1: transport error
[16:54:01 ✓:0,✗:0,⠇:2] │││││ ║     2: error trying to connect: tcp connect error: Connection refused (os error 111)
[16:54:01 ✓:0,✗:0,⠇:2] │││││ ║     3: tcp connect error: Connection refused (os error 111)
[16:54:01 ✓:0,✗:0,⠇:2] │││││ ║     4: Connection refused (os error 111)
[16:54:01 ✓:0,✗:0,⠇:2] │││││ ╚════════════════════════
[16:54:01 ✓:0,✗:0,⠇:2] ││││└─▶ERROR 409ms
[16:54:01 ✓:0,✗:0,⠇:2] │││└[build and run client]─▶[OK,ERROR] 40s
[16:54:03 ✓:0,✗:0,⠇:2] │││ (waiting for completion)
[16:54:03 ✓:0,✗:0,⠇:2] ││└[background loader]─▶ERROR
End-to-end tests for the launcher and enclave binary ❯ run Virtual variant ❯ background loader ╔════════════════════════
End-to-end tests for the launcher and enclave binary ❯ run Virtual variant ❯ background loader ║ ════╡ stderr ╞════
End-to-end tests for the launcher and enclave binary ❯ run Virtual variant ❯ background loader ║ [2023-01-12T16:53:15Z INFO  oak_functions_launcher::instance::virtualized] Executing: Command { std: "/usr/bin/qemu-system-x86_64" "-enable-kvm" "-cpu" "IvyBridge-IBRS,enforce" "-nodefaults" "-nographic" "-no-reboot" "-machine" "microvm,acpi=on" "-chardev" "socket,id=consock,fd=13" "-serial" "chardev:consock" "-chardev" "socket,id=commsock,fd=15" "-device" "virtio-serial-device,max_ports=1" "-device" "virtconsole,chardev=commsock" "-device" "loader,file=./oak_functions_enclave/target/x86_64-unknown-none/debug/oak_functions_enclave" "-bios" "./stage0/target/x86_64-unknown-none/release/oak_stage0.bin", kill_on_drop: false }
End-to-end tests for the launcher and enclave binary ❯ run Virtual variant ❯ background loader ║ [2023-01-12T16:53:15Z INFO  oak_functions_launcher] read Wasm file from disk ./oak_functions_launcher/key_value_lookup.wasm (1728193 bytes)
End-to-end tests for the launcher and enclave binary ❯ run Virtual variant ❯ background loader ║ Could not access KVM kernel module: Permission denied
End-to-end tests for the launcher and enclave binary ❯ run Virtual variant ❯ background loader ║ qemu-system-x86_64: failed to initialize kvm: Permission denied
End-to-end tests for the launcher and enclave binary ❯ run Virtual variant ❯ background loader ║ thread 'tokio-runtime-worker' panicked at 'couldn't send lookup data: Status { code: Internal, message: "" }', oak_functions_launcher/src/main.rs:134:21
End-to-end tests for the launcher and enclave binary ❯ run Virtual variant ❯ background loader ║ note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
End-to-end tests for the launcher and enclave binary ❯ run Virtual variant ❯ background loader ║ thread 'main' panicked at 'couldn't initialize the service: Status { code: Internal, message: "" }', oak_functions_launcher/src/main.rs:161:10
End-to-end tests for the launcher and enclave binary ❯ run Virtual variant ❯ background loader ╚════════════════════════
[16:54:03 ✓:0,✗:0,⠇:2] │└[run Virtual variant]─▶[OK,ERROR] 112s
[16:54:03 ✓:0,✗:1,⠇:1] └[End-to-end tests for the launcher and enclave binary]─▶[OK,ERROR] 112s

```

**Comment by tiziano88** [comment]
FWIW it works on my machine :tm: 

From inside docker I see the same:

```console
$ ls -als /dev/kvm 
0 crw-rw----+ 1 nobody nogroup 10, 232 Jan 12 17:27 /dev/kvm
```

From the host:

```console
$ ls -als /dev/kvm
0 crw-rw----+ 1 root kvm 10, 232 Jan 12 17:27 /dev/kvm
```

I thought I was part of the `kvm` group, but actually it does not seem so; so I am actually not sure why it is working for me.

**Comment by conradgrobler** [comment]
I think that this is because of sudo-less docker. Your user account outside of the container also needs access to KVM.

This could either be done by adding the user to the KVM group on the host, or running

``` bash
sudo setfacl -m u:${USER}:rw /dev/kvm
```
