### ISSUE TITLE
Load 2 GiB of lookup data

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#3668]
Currently we can load at most 2 GiB of lookup data due to proto limits.

When we attempt to add more, we [fail](https://github.com/project-oak/oak/blob/dd6f7488e83e1e58b116276478af6120cc92f67b/oak_functions_launcher/src/main.rs#L131)

```
thread 'test_load_large_lookup_data' panicked at 'couldn't convert the message length usize to u32: TryFromIntError(())', oak_channel/src/message.rs:58:14
stack backtrace:
...
thread 'test_load_large_lookup_data' panicked at 'couldn't send lookup data: Status { code: Internal, message: "failed when invoking the request_dispatcher: request channel closed" }', /workspace/oak_functions_launcher/src/lib.rs:116:9

```

**Comment by mariaschett** [comment]
Fixed by:
* Receive more than 2 GiB in the Lookup Data Manager:  #3718
* Send more from launcher size: #3736
