### ISSUE TITLE
No failure from panic in Rust unit test

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#905]
The most [recent build](https://pantheon.corp.google.com/cloud-build/builds/53c46069-237c-4074-8520-23e8326ee3ba;step=8?project=oak-ci) of `master` shows a `panic!` happening in an `oak_runtime` test (below).  However, the build was marked as successful.

So we need to figure out a way of ensuring that `panic!`s trigger a build failure.  

[Just setting `panic = "abort"` in a `[profile.test]` section in `Cargo.toml` doesn't work; `cargo test` is always `panic = "unwind"` (because the test framework needs to be able to handle death tests).]

```log
thread 'WasmNode(test)' panicked at 'remove_node_id: No such node_id NodeId(1)', oak/server/rust/oak_runtime/src/runtime/mod.rs:716:40
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  13: oak_runtime::runtime::Runtime::remove_node_id::{{closure}}
             at oak/server/rust/oak_runtime/src/runtime/mod.rs:716
  14: core::option::Option<T>::unwrap_or_else
             at /rustc/58b834344fc7b9185e7a50db1ff24e5eb07dae5e/src/libcore/option.rs:422
  15: oak_runtime::runtime::Runtime::remove_node_id
             at oak/server/rust/oak_runtime/src/runtime/mod.rs:714
  16: oak_runtime::runtime::RuntimeProxy::exit_node
             at oak/server/rust/oak_runtime/src/runtime/mod.rs:912
  17: oak_runtime::node::wasm::WasmNode::worker_thread
             at oak/server/rust/oak_runtime/src/node/wasm/mod.rs:977
  18: <oak_runtime::node::wasm::WasmNode as oak_runtime::node::Node>::start::{{closure}}
             at oak/server/rust/oak_runtime/src/node/wasm/mod.rs:1009
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test node::wasm::tests::wasm_starting_minimal_module_succeeds ... ok

```

**Comment by daviddrysdale** [comment]
I believe this should now be fixed, thanks to [@tiziano88's observation](https://github.com/project-oak/oak/pull/978#discussion_r424653573).  Previously threads created in `oak_runtime` tests were never joined, so any `panic` on a test node thread would never make it to the test runner.
